@echo off

chcp 65001 >nul

cls
adb wait-for-device
adb devices
echo "Uninstall bloat apps? (NOT RECOMMENDED)"
set /p input="yes/no >_: "
if /i "%input%"=="yes" goto :start
goto :tweaks

:start
    powershell -c "adb shell pm list packages -3 |
    ForEach-Object {
        $packageName = $_ -replace '^package:', ''
        adb shell pm uninstall -k --user 0 $packageName
    }"

    powershell -c "adb shell pm list packages -s |
    ForEach-Object {
        $packageName = $_ -replace '^package:', ''
        adb shell pm clear --user 0 $packageName
    }"

    powershell -c "adb shell pm list packages |
    ForEach-Object {
        $packageName = $_ -replace '^package:', ''
        adb shell pm reset-permissions -p $packageName
        adb shell cmd appops set $packageName WAKE_LOCK deny
        adb shell cmd appops set $packageName RUN_IN_BACKGROUND deny
        adb shell cmd appops set $packageName RUN_ANY_IN_BACKGROUND deny
        adb shell cmd appops set $packageName START_FOREGROUND deny
        adb shell cmd appops set $packageName INSTANT_APP_START_FOREGROUND deny
        adb shell cmd appops set $packageName ACCESS_RESTRICTED_SETTINGS deny
        adb shell cmd appops write-settings
    }"

    adb shell pm uninstall --user 0 com.google.android.googlequicksearchbox

:tweaks
    echo "Applying Tweaks ..."
    adb shell device_config put runtime_native_boot pin_camera false
    adb shell device_config put launcher ENABLE_QUICK_LAUNCH_V2 true
    adb shell device_config put launcher enable_quick_launch_v2 true
    adb shell device_config put privacy location_access_check_enabled false
    adb shell device_config put privacy location_accuracy_enabled false
    adb shell device_config put privacy safety_protection_enabled true
    adb shell device_config put activity_manager use_compaction true
    adb shell device_config put activity_manager set_sync_disabled_for_tests persistent
    adb shell device_config put activity_manager enable_background_cpu_boost true
    adb shell device_config put activity_manager force_high_refresh_rate true
    adb shell device_config put graphics render_thread_priority high
    adb shell device_config put graphics enable_gpu_boost true
    adb shell device_config put graphics enable_cpu_boost true
    adb shell device_config put surfaceflinger set_max_frame_rate_multiplier 0.5
    adb shell device_config put systemui window_cornerRadius 0
    adb shell device_config put systemui window_blur 0
    adb shell device_config put systemui window_shadow 0
    adb shell dumpsys deviceidle whitelist +com.android.systemui
    adb shell dumpsys deviceidle whitelist +com.sec.android.app.launcher
    adb shell dumpsys power set_sampling_rate 0
    adb shell svc data disable
    adb shell cmd shortcut reset-all-throttling
    adb shell cmd power set-fixed-performance-mode-enabled true
    adb shell cmd power set-adaptive-power-saver-enabled false
    adb shell cmd power set-mode 0
    adb shell cmd netpolicy set restrict-background true
    adb shell cmd activity idle-maintenance
    adb shell cmd thermalservice override-status 1
    adb shell cmd looper_stats disable
    adb shell cmd display ab-logging-disable
    adb shell cmd display dwb-logging-disable
    adb shell pm trim-caches 999999M
    adb shell pm compile -a -f --check-prof false -m speed
    adb shell pm compile -a -f --secondary-dex --check-prof false -m speed
    adb shell pm compile -a -f --check-prof false --compile-layouts
    adb shell pm trim-caches 999999M
    adb shell wipe cache
    adb shell recovery --wipe_cache
    adb shell rm -rf /cache/*.apk
    adb shell rm -rf /cache/*.tmp
    adb shell rm -rf /cache/*.log
    adb shell rm -rf /data/log/*
    adb shell rm -rf /data/*.log
    adb shell rm -rf /data/mlog/*
    adb shell rm -rf /data/klog/*
    adb shell rm -rf /data/ap-log/*
    adb shell rm -rf /data/cp-log/*
    adb shell rm -rf /data/last_alog
    adb shell rm -rf /data/last_kmsg
    adb shell rm -rf /data/dontpanic/*
    adb shell rm -rf /data/memorydump/*
    adb shell rm -rf /data/dumplog/*
    adb shell rm -rf /data/rdr/*
    adb shell rm -rf /data/adb/*
    adb shell rm -rf /data/tombstones/*
    adb shell rm -rf /data/backup/pending/*
    adb shell rm -rf /data/system/dropbox/*
    adb shell rm -rf /data/system/usagestats/*
    adb shell rm -rf /data/anr/*
    adb shell rm -rf /data/crashdata/*
    adb shell rm -rf /data/dalvik-cache/*
    adb shell rm -rf /data/data/*/cache/*
    adb shell rm -rf /data/cache/*.*
    adb shell rm -rf /data/resource-cache/*
    adb shell rm -rf /data/local/*
    adb shell rm -rf /data/clipboard/*
    adb shell rm -rf /dev/log/main/*
    adb shell rm -rf /sdcard/log/*
    adb shell rm -rf /sdcard/LogService/*
    adb shell rm -rf /storage/sdcard0/LogService/*
    adb shell rm -rf /storage/sdcard1/LogService/*
    adb shell rm -rf /storage/sdcard0/LOST.DIR/*
    adb shell rm -rf /storage/sdcard1/LOST.DIR/*
    adb shell pm trim-caches 999999M
    adb shell sm fstrim
    adb shell cmd stats write-to-disk
    adb shell sync

    for /f "delims=" %%d in ('adb shell ls -a sdcard') do (adb shell touch "sdcard/%%d/.metadata_never_index" "sdcard/%%d/.noindex" "sdcard/%%d/.nomedia" "sdcard/%%d/.trackerignore")

    adb shell logcat -P ""
    adb shell logcat -c

    adb shell setprop persist.log.tag S

    adb shell wm scaling off
    adb shell wm disable-blur true
    adb shell wm set-sandbox-display-apis true

    adb shell settings put secure user_setup_complete 1
    adb shell settings put global user_experience_enabled 0
    adb shell settings put global DEVICE_PROVISIONED 1
    adb shell settings put global ro.revision 0
    adb shell settings put global ro.rom.zone 2
    adb shell settings put global ro.config.rom_lite_old_features true
    adb shell settings put global ro.setupwizard.enterprise_mode 1
    adb shell settings put global ro.fps_enable 1
    adb shell settings put global ro.fps.capsmin 60
    adb shell settings put global debug.fps.render.fast 1
    adb shell settings put global dont.lower.fps true
    adb shell settings put global stabilizer.fps true
    adb shell settings put global stable.fps.enable true
    adb shell settings put global ro.vendor.display.touch.idle.enable true
    adb shell settings put global persist.vendor.disable_idle_fps true
    adb shell settings put global vendor.display.enable_default_color_mode 1
    adb shell settings put global vendor.display.disable_scaler 0
    adb shell settings put global vendor.display.disable_excl_rect 0
    adb shell settings put global vendor.display.disable_excl_rect_partial_fb 1
    adb shell settings put global vendor.display.enable_async_powermode 1
    adb shell settings put global vendor.display.disable_inline_rotator 1
    adb shell settings put global vendor.display.disable_ext_anim 1
    adb shell settings put global vendor.display.idle_time 0
    adb shell settings put global vendor.display.idle_time_inactive 0
    adb shell settings put global vendor.display.enhance_idle_time 1
    adb shell settings put global vendor.display.enable_optimize_refresh 1
    adb shell settings put global vendor.display.disable_metadata_dynamic_fps 1
    adb shell settings put global vendor.display.use_smooth_motion 1
    adb shell settings put global vendor.display.enable_camera_smooth 1
    adb shell settings put global camera.disable_zsl_mode 1
    adb shell settings put global debug.refresh_rate.view_override 1
    adb shell settings put global debug.threadedOpt 1
    adb shell settings put secure thread_priority highest HIGHEST
    adb shell settings put secure support_highfps 1
    adb shell settings put secure refresh_rate_mode 2
    adb shell settings put secure user_wait_timeout 0
    adb shell settings put system thermal_limit_refresh_rate 0
    adb shell settings put system min_frame_rate 60.0
    adb shell settings put system min_refresh_rate 60.0
    adb shell settings put system display_color_mode 0
    adb shell settings put system remove_animations 1
    adb shell settings put system reduce_animations 1
    adb shell settings put system slider_animation_duration 250
    adb shell settings put global window_animation_scale 0.25
    adb shell settings put global transition_animation_scale 0.25
    adb shell settings put global animator_duration_scale 0.0
    adb shell settings put global remove_animations 1
    adb shell settings put global fancy_ime_animations 0
    adb shell settings put global visual_bars false
    adb shell settings put global reduce_transitions 1
    adb shell settings put global shadow_animation_scale 0
    adb shell settings put global render_shadows_in_compositor true
    adb shell settings put global window_focus_timeout 250
    adb shell settings put global ro.launcher.anim.app.exit false
    adb shell settings put global ro.launcher.anim.launchtask false
    adb shell settings put global persist.sys.rotationanimation false
    adb shell settings put global sys.rotation.animscale 0.25
    adb shell settings put global sys.disable_ext_animation 1
    adb shell settings put global sys.enable_grip_rejection 1
    adb shell settings put global sys.refresh.dirty 0
    adb shell settings put global ro.input.noresample 1
    adb shell settings put global ro.config.enable_touchboost true
    adb shell settings put global ro.vendor.touchfeature.gamemode.enable true
    adb shell settings put global ro.floatingtouch.available 1
    adb shell settings put global ro.toastshow.enable false
    adb shell settings put global view.touch_slop 1
    adb shell settings put global view.scroll_friction 0
    adb shell settings put global view.fading_edge_length 1
    adb shell settings put global persist.touch_vsync_opt 1
    adb shell settings put global persist.touch_move_opt 1
    adb shell settings put global touch_calibration 1
    adb shell settings put global touch.size.bias 0
    adb shell settings put global touch.size.isSummed 0
    adb shell settings put global touch.size.scale 1
    adb shell settings put global touch.pressure.scale 0.1
    adb shell settings put global touch.distance.scale 0
    adb shell settings put secure touch_blocking_period 0.0
    adb shell settings put secure tap_duration_threshold 0.0
    adb shell settings put secure long_press_timeout 250
    adb shell settings put secure multi_press_timeout 250
    adb shell settings put secure speed_mode_enable 1
    adb shell settings put system speed_mode 1
    adb shell settings put global speed_mode_on 1
    adb shell settings put global enable_hardware_acceleration 1
    adb shell settings put global hardware_accelerated_rendering_enabled 1
    adb shell settings put global hardware_accelerated_graphics_decoding 1
    adb shell settings put global hardware_accelerated_video_decode 1
    adb shell settings put global hardware_accelerated_video_encode 1
    adb shell settings put global hardwareAccelerated true
    adb shell settings put global media.sf.hwaccel 1
    adb shell settings put global video.accelerate.hw 1
    adb shell settings put global ro.config.enable.hw_accel true
    adb shell settings put global ro.config.hw_voicerecord true
    adb shell settings put global hwui.private_hal_readback 1
    adb shell settings put global debug.hwui.render_priority 1
    adb shell settings put global debug.hwui.use_partial_updates false
    adb shell settings put global debug.hwui.show_layers_updates false
    adb shell settings put global debug.hwui.show_layer_grid 0
    adb shell settings put global debug.hwui.show_layer_bounds 0
    adb shell settings put global debug.hwui.overdraw false
    adb shell settings put global debug.hwui.profile false
    adb shell settings put global debug.hwui.use_d2d 1
    adb shell settings put global debug.hwui.use_hint_manager false
    adb shell settings put global ro.vendor.hwui.platform 1
    adb shell settings put global ro.hwui.renderer.disable_opaque true
    adb shell settings put global ro.hwui.disable_scissor_opt false
    adb shell settings put global ro.hwui.texture_cache_size 20
    adb shell settings put global ro.hwui.texture_cache_flush_rate 0.5
    adb shell settings put global ro.hwui.gradient_cache_size 0.1
    adb shell settings put global ro.hwui.drop_shadow_cache_size 1
    adb shell settings put global ro.hwui.shape_cache_size 1
    adb shell settings put global ro.hwui.r_buffer_cache_size 1
    adb shell settings put global ro.hwui.path_cache_size 1
    adb shell settings put global ro.hwui.disable_asset_atlas true
    adb shell settings put global ro.hwui.layer_cache_size 1
    adb shell settings put global persist.texture_cache_opt 1
    adb shell settings put global disable_hw_overlays 1
    adb shell settings put global overlay_disable_force_hwc 1
    adb shell settings put global renderthread.skia.reduceopstasksplitting true
    adb shell settings put global skia.force_gl_texture 1
    adb shell settings put global omap.enhancement true
    adb shell settings put global ENFORCE_PROCESS_LIMIT false
    adb shell settings put global restricted_device_performance 1,0
    adb shell settings put global sem_enhanced_cpu_responsiveness 1
    adb shell settings put global enhanced_cpu_responsiveness 1
    adb shell settings put global enhanced_processing 2
    adb shell settings put global debug.multicore.processing 1
    adb shell settings put global GPUTURBO_SWITCH 1
    adb shell settings put global GPUTUNER_SWITCH 1
    adb shell settings put global zen_mode 2
    adb shell settings put global game_low_latency_mode 1
    adb shell settings put global game_gpu_optimizing 1
    adb shell settings put global game_driver_mode 1
    adb shell settings put global game_driver_all_apps 1
    adb shell settings put global game_driver_opt_out_apps 1
    adb shell settings put global updatable_driver_all_apps 1
    adb shell settings put global updatable_driver_production_opt_out_apps 1
    adb shell settings put global persist.sys.cfu_auto 0
    adb shell settings put global ntp_server null
    adb shell settings put global network_avoid_bad_wifi 1
    adb shell settings put global network_recommendations_enabled -1
    adb shell settings put global network_scoring_ui_enabled 0
    adb shell settings put global netstats_enabled 0
    adb shell settings put global wifi_watchdog_on 0
    adb shell settings put global wifi_watchdog_roaming 0
    adb shell settings put global wifi.supplicant_scan_interval 300
    adb shell settings put global wifi_framework_scan_interval_ms 0
    adb shell settings put global wifi_scan_throttle_enabled 0
    adb shell settings put global wifi_scan_always_enabled 0
    adb shell settings put global ble_scan_always_enabled 0
    adb shell settings put global hotword_detection_enabled 0
    adb shell settings put global mobile_data_always_on 0
    adb shell settings put global mobile_data_keepalive_enabled 0
    adb shell settings put global default_restrict_background_data 1
    adb shell settings put global background_data 0
    adb shell settings put global data_roaming_settings 0
    adb shell settings put global data_roaming_int 0
    adb shell settings put global data_roaming 0
    adb shell settings put global data_saver_mode 1
    adb shell settings put global ro.wifi.signal.optimized true
    adb shell settings put global ro.sf.wifi_sleep_policy_default 2
    adb shell settings put global ro.mds.enable true
    adb shell settings put global ro.ril.hep 1
    adb shell settings put global ro.mtk_lte_support 1
    adb shell settings put global lte_category 4
    adb shell settings put global persist.radio.lte_enabled true
    adb shell settings put global ro.config.hw_lte_support true
    adb shell settings put global ro.config.hw_volte_on true
    adb shell settings put global ro.config.hw_volte_dyn true
    adb shell settings put global ro.config.full_network_support true
    adb shell settings put global persist.eons.enabled true
    adb shell settings put global persist.cust.tel.eons 1
    adb shell settings put global persist.sys.klo on
    adb shell settings put global persist.sys.once_scan true
    adb shell settings put global persist.mot.gps.conf.from.sim false
    adb shell settings put global persist.mot.gps.smart_battery 1
    adb shell settings put global persist.mot.gps.assisted false
    adb shell settings put global ro.mot.proximity.jitter false
    adb shell settings put global ro.mot.eri.losalert.delay 1000
    adb shell settings put global ro.telephony.call_ring.delay 0
    adb shell settings put global persist.sys.job_delay false
    adb shell settings put global persist.sys.memopt.switch 1
    adb shell settings put global persist.sys.fuse.passthrough.enable true
    adb shell settings put global persist.sys.art.opt.enable true
    adb shell settings put global persist.sys.dalvik.multithread true
    adb shell settings put global persist.sys.dalvik.hyperthreading true
    adb shell settings put global dalvik.vm.dex2oat64.enabled true
    adb shell settings put global dalvik.vm.heaputilization 0.25
    adb shell settings put global dalvik.vm.heaptargetutilization 0.25
    adb shell settings put global dalvik.vm.heapminfree 1m
    adb shell settings put global dalvik.vm.dex2oat-swap true
    adb shell settings put global dalvik.vm.verify-bytecode false
    adb shell settings put global dalvik.vm.usejit true
    adb shell settings put global dalvik.vm.usejitprofiles true
    adb shell settings put global dalvik.vm.checkjni false
    adb shell settings put global dalvik.vm.check-dex-sum false
    adb shell settings put global dalvik.vm.debug.alloc 0
    adb shell settings put global dalvik.vm.dexopt-data-only 1
    adb shell settings put global dalvik.vm.dexopt-flags m=y,v=n,o=y,u=n
    adb shell settings put global dalvik.vm.execution-mode int:jit
    adb shell settings put global dalvik.vm.dexopt.secondary true
    adb shell settings put global dalvik.vm.dexopt.thermal-cutoff 2
    adb shell settings put global dalvik.vm.dex2oat-filter interpret-only
    adb shell settings put global dalvik.vm.deadlock-predict off
    adb shell settings put global dalvik.vm.dex2oat-backend Quick
    adb shell settings put global dalvik.vm.dex2oat-minidebuginfo false
    adb shell settings put global dalvik.vm.dex2oat-resolve-startup-strings false
    adb shell settings put global dalvik.vm.madvise-random true
    adb shell settings put global dalvik.vm.foreground-heap-growth-multiplier 1.0
    adb shell settings put global dalvik.vm.jit.codecachesize 1
    adb shell settings put global dalvik.vm.appimageformat lz4
    adb shell settings put global dalvik.vm.systemservercompilerfilter speed
    adb shell settings put global dalvik.vm.systemuicompilerfilter speed
    adb shell settings put global dalvik.vm.houdini on
    adb shell settings put global dalvik.vm.zygotemaxfailedboots 3
    adb shell settings put global persist.vm.stackdump.threshold 0
    adb shell settings put global vm.scan_unevictable_pages 0
    adb shell settings put global dalvik.gc.type precise
    adb shell settings put global top_app_dexopt_with_speed_profile true
    adb shell settings put global pm.dexopt.nsys-library quicken
    adb shell settings put global pm.dexopt.core-app quicken
    adb shell settings put global pm.dexopt.shared quicken
    adb shell settings put global pm.dexopt.boot verify-at-runtime
    adb shell settings put global pm.dexopt.first-boot quicken
    adb shell settings put global pm.dexopt.install quicken
    adb shell settings put global pm.dexopt.bg-dexopt quicken
    adb shell settings put global pm.dexopt.ab-ota quicken
    adb shell settings put global pm.dexopt.forced-dexopt quicken
    adb shell settings put global ro.dex.async.opt 1
    adb shell settings put global ro.config.vm_prioritymode 2
    adb shell settings put global ro.dalvik.vm.native.bridge 0
    adb shell settings put global persist.sys.nativebridge 1
    adb shell settings put global ro.malloc.impl jemalloc
    adb shell settings put global ro.maple.enable 1
    adb shell settings put global tombstoned.max_tombstone_count 20
    adb shell settings put global sys.hwsholder.count 0
    adb shell settings put global vnswap.enabled false
    adb shell settings put global cgroup_disable memory
    adb shell settings put global ro.systemui.burn_in_protection true
    adb shell settings put global ro.config.hw_simpleui_enable 1
    adb shell settings put global ro.config.hw_dsda true
    adb shell settings put global ro.config.hw_dts true
    adb shell settings put global ro.config.hw_disable_cops true
    adb shell settings put global ro.config.hw_accesscontrol false
    adb shell settings put global ro.config.hw_restrict_gps true
    adb shell settings put global ro.config.updatelocation false
    adb shell settings put global ro.config.delay_send_signal false
    adb shell settings put global sys_traced 0
    adb shell settings put global persist.traced.enable 0
    adb shell settings put global persist.traced_perf.enable 0
    adb shell settings put global wifi_verbose_logging_enabled 0
    adb shell settings put global send_action_app_error 0
    adb shell settings put global send_action_app_error_native 0
    adb shell settings put global foreground_service_starts_logging_enabled 0
    adb shell settings put global enable_diskstats_logging 0
    adb shell settings put global activity_starts_logging_enabled 0
    adb shell settings put global ro.config.nocheckin 1
    adb shell settings put global profiler.force_disable_err_rpt 1
    adb shell settings put global profiler.force_disable_ulog 1
    adb shell settings put global profiler.debugmonitor false
    adb shell settings put global profiler.launch false
    adb shell settings put global logcat.live disable
    adb shell settings put global config.disable_consumerir true
    adb shell settings put global ro.debuggable 0
    adb shell settings put global debug.mdpcomp.logs 0
    adb shell settings put global ro.kernel.checkjni 0
    adb shell settings put global debug.atrace.tags.enableflags 0
    adb shell settings put global logd.kernel false
    adb shell settings put global vendor.display.disable_hw_recovery_dump 1
    adb shell settings put global profiler.hung.dumpdobugreport false
    adb shell settings put global trustkernel.log.state disable
    adb shell settings put global debug.systemui.latency_tracking 0
    adb shell settings put global persist.sample.eyetracking.log 0
    adb shell settings put global media.metrics.enabled 0
    adb shell settings put global media.metrics 0
    adb shell settings put global debug.brcm.mm.logs 0
    adb shell settings put global persist.sys.miui_optimization true
    adb shell settings put global sys.miui.ndcd off
    adb shell settings put global sys.debug.watchdog 0
    adb shell settings put global logd.logpersistd.enable false
    adb shell settings put global logd.statistics 0
    adb shell settings put global config.stats 0
    adb shell settings put global persist.sys.watchdog_enhanced false
    adb shell settings put global persist.sys.oom_crash_on_watchdog false
    adb shell settings put global persist.sys.logging 0
    adb shell settings put global persist.sys.loglevel 0
    adb shell settings put global sys.log.app 0
    adb shell settings put global ro.logd.size 0
    adb shell settings put global ro.logd.size.stats 0
    adb shell settings put global ro.logdumpd.enabled 0
    adb shell settings put global persist.anr.dumpthr 0
    adb shell settings put global persist.vendor.dpm.loglevel 0
    adb shell settings put global persist.vendor.dpmhalservice.loglevel 0
    adb shell settings put global persist.vendor.sys.core.enabled 0
    adb shell settings put global persist.vendor.sys.modem.logging.enable false
    adb shell settings put global debug.enable.wl_log 0
    adb shell settings put global debug.als.logs 0
    adb shell settings put global debug.svi.logs 0
    adb shell settings put global log.tag.stats_log 0
    adb shell settings put global ro.lmk.debug false
    adb shell settings put global ro.lmk.log_stats false
    adb shell settings put global sys.lmk.reportkills false
    adb shell settings put global persist.sys.lmk.reportkills false
    adb shell settings put global ro.config.hw.logsystem.send 0
    adb shell settings put global show_non_market_apps_error 0
    adb shell settings put global anr_show_error_cause false
    adb shell settings put global debug.hwui.skia_atrace_enabled false
    adb shell settings put global persist.sys.mdlog_dumpback 0
    adb shell settings put global persist.vendor.mdlog.need_dump 0
    adb shell settings put global vendor.swvdec.log.level 0
    adb shell settings put global debug.sf.enable_transaction_tracing false
    adb shell settings put global persist.vendor.console.silent.config 1
    adb shell settings put global persist.vendor.recovery_update false
    adb shell settings put global persist.binder.check.enable false
    adb shell settings put global ro.statsd.enable false
    adb shell settings put global ro.systemui.debug false
    adb shell settings put global ro.have_aee_feature 0
    adb shell settings put global ro.aee.enforcing no
    adb shell settings put global ro.aee.enperf off
    adb shell settings put global ro.vendor.tran_perf_plus 1
    adb shell settings put global persist.vendor.product.perf 1
    adb shell settings put global persist.debug.sf.statistics 0
    adb shell settings put global persist.sys.crash_dumps 0
    adb shell settings put global persist.sys.pstore_dumps 0
    adb shell settings put global persist.debug.host.ramdump 0
    adb shell settings put global persist.radio.ramdump 0
    adb shell settings put global persist.ims.disableDebugLogs 1
    adb shell settings put global persist.ims.disableDebugDataPathLogs 1
    adb shell settings put global persist.ims.disableADBLogs 1
    adb shell settings put global persist.ims.disableQXDMLogs 1
    adb shell settings put global persist.ims.disableIMSLogs 1
    adb shell settings put global persist.ims.disableSigHandler 1
    adb shell settings put global persist.sys.qxdm no
    adb shell settings put global persist.sys.qxdm_logs 0
    adb shell settings put global app_usage_enabled 0
    adb shell settings put global package_usage_stats_enabled 0
    adb shell settings put global recent_usage_data_enabled 0
    adb shell settings put global persist.service.debuggable 0
    adb shell settings put global persist.logd.limit off
    adb shell settings put global persist.logd.size 0
    adb shell settings put global persist.bt.iot.enablelogging false
    adb shell settings put global vendor.bluetooth.startbtlogger false
    adb shell settings put global ro.vendor.connsys.dedicated.log 0
    adb shell settings put global ro.hw_disable_instantonline true
    adb shell settings put global sys.wifitracing.started 0
    adb shell settings put global persist.zygote.core_dump 0
    adb shell settings put global persist.ai.timedebug.enable false
    adb shell settings put global persist.sys.qlogd 0
    adb shell settings put global persist.sys.hw_statistics 0
    adb shell settings put global persist.sys.apps_statistics 0
    adb shell settings put global persist.sys.apr.enabled 0
    adb shell settings put global persist.vendor.aprservice.enabled 0
    adb shell settings put global persist.vendor.verbose_logging_enabled false
    adb shell settings put global persist.vendor.sys.fp.dump_data 0
    adb shell settings put global persist.debug.xlog.enable 0
    adb shell settings put global persist.meta.dumpdata 0
    adb shell settings put global persist.oem.dump 0
    adb shell settings put global persist.service.crash.enable 0
    adb shell settings put global persist.sys.perfettologging.enable 0
    adb shell settings put global persist.sys.perf.debug false
    adb shell settings put global persist.sys.offlinelog.kernel false
    adb shell settings put global persist.sys.offlinelog.logcat false
    adb shell settings put global persist.sys.offlinelog.logcatkernel false
    adb shell settings put global persist.sys.log.user 0
    adb shell settings put global persist.sys.log-main.enable 0
    adb shell settings put global persist.sys.log-system.enable 0
    adb shell settings put global persist.sys.log-events.enable 0
    adb shell settings put global persist.sys.log-radio.enable 0
    adb shell settings put global persist.sys.tcpdump.lognum 0
    adb shell settings put global persist.sys.tcpdump.logsize 0
    adb shell settings put global persist.sys.wifipacketlog.state false
    adb shell settings put global persist.net.monitor false
    adb shell settings put global persist.debug.wfd.enable 0
    adb shell settings put global persist.data.qmi.adb_logmask 0
    adb shell settings put global sys.deepdiagnose.support 0
    adb shell settings put global ro.bionic.ld.warning 0
    adb shell settings put global ro.platform.has.systemlog false
    adb shell settings put global ro.vendor.qfusion_use_report_period false
    adb shell settings put system status_logging_cnt 0
    adb shell settings put system anr_debugging_mechanism 0
    adb shell settings put system anr_debugging_mechanism_status 0
    adb shell settings put system send_security_reports 0
    adb shell settings put system remote_control 0
    adb shell settings put system dk_log_level 0
    adb shell settings put system user_log_enabled 0
    adb shell settings put system window_orientation_listener_log 0
    adb shell settings put system rakuten_denwa 0
    adb shell settings put system mcf_continuity 0
    adb shell settings put system mcf_continuity_permission_denied 1
    adb shell settings put system mcf_permission_denied 1
    adb shell settings put system multicore_packet_scheduler 1
    adb shell settings put secure limit_ad_tracking 1
    adb shell settings put secure usage_metrics_marketing_enabled 0
    adb shell settings put secure USAGE_METRICS_UPLOAD_ENABLED 0
    adb shell settings put secure upload_apk_enable 0
    adb shell settings put secure upload_debug_log_pref 0
    adb shell settings put secure upload_log_pref 0
    adb shell settings put secure backup_enabled 0
    adb shell settings put secure location_providers_allowed -gps,-network,-wifi
    adb shell settings put secure mock_location 1
    adb shell settings put secure adaptive_connectivity_enabled 0
    adb shell settings put secure bluetooth_hci_log 0
    adb shell settings put secure ssl_session_cache null
    adb shell settings put global multipath-tcp-enable 1
    adb shell settings put global sys.net.support.netprio true
    adb shell settings put global dns_resolvability_required 0
    adb shell settings put global net.dns1 194.242.2.9
    adb shell settings put global net.dns2 194.242.2.9
    adb shell settings put global private_dns_mode hostname
    adb shell settings put global private_dns_specifier all.dns.mullvad.net
    adb shell settings put global webview_safe_browsing_enabled 0
    adb shell settings put global wifi_mac_randomization 2
    adb shell settings put global wifi_connected_mac_randomization_supported 2
    adb shell settings put global wifi_safe_mode 1
    adb shell settings put global wifi_stability 1
    adb shell settings put global wifi_suspend_optimizations_enabled 2
    adb shell settings put global wifi_always_requested 0
    adb shell settings put global persist.mm.sta.enable 0
    adb shell settings put global ro.data.large_tcp_window_size true
    adb shell settings put global persist.data.tcp_rst_drop true
    adb shell settings put global ro.config.hw_new_wifitopdp 1
    adb shell settings put global ro.config.hw_wifipro_enable true
    adb shell settings put global ro.config.wifi_fast_bss_enable true
    adb shell settings put global config.disable_rtt true
    adb shell settings put global ro.config.hw_privacymode true
    adb shell settings put global ro.config.hw_perfhub true
    adb shell settings put global ro.config.hw_perfgenius true
    adb shell settings put global ro.config.enable_perfhub_fling true
    adb shell settings put global persist.perf.level 2
    adb shell settings put global vidc.debug.perf.mode 2
    adb shell settings put global vidc.debug.level 0
    adb shell settings put global libc.debug.malloc 0
    adb shell settings put global debug.syncopts 3
    adb shell settings put global debug.hwc.logvsync 0
    adb shell settings put global debug.hwc.nodirtyregion 1
    adb shell settings put global debug.hwc.force_gpu 1
    adb shell settings put global debug.hwc.force_gpu_vsync 1
    adb shell settings put global debug.hwc.fakevsync 1
    adb shell settings put global debug.hwc.otf 1
    adb shell settings put global debug.hwc.winupdate 1
    adb shell settings put global debug.hwc.disabletonemapping true
    adb shell settings put global debug.hwui.use_buffer_age false
    adb shell settings put global persist.alloc_buffer_sync true
    adb shell settings put global CPU_MIN_CHECK_DURATION false
    adb shell settings put global MIN_CRASH_INTERVAL false
    adb shell settings put global GC_MIN_INTERVAL false
    adb shell settings put global GC_TIMEOUT false
    adb shell settings put global SERVICE_TIMEOUT false
    adb shell settings put global PROC_START_TIMEOUT false
    adb shell settings put global MAX_PROCESSES false
    adb shell settings put global MAX_ACTIVITIES false
    adb shell settings put global MAX_SERVICE_INACTIVITY false
    adb shell settings put global MIN_RECENT_TASKS false
    adb shell settings put global MAX_RECENT_TASKS false
    adb shell settings put global ACTIVITY_INACTIVITY_RESET_TIME false
    adb shell settings put global APP_SWITCH_DELAY_TIME false
    adb shell settings put global CONTENT_APP_IDLE_OFFSET false
    adb shell settings put global foreground_mem_priority high
    adb shell settings put global ro.FOREGROUND_APP_ADJ 0
    adb shell settings put global ro.HOME_APP_ADJ 1
    adb shell settings put global ro.VISIBLE_APP_ADJ 2
    adb shell settings put global ro.PERCEPTIBLE_APP_ADJ 3
    adb shell settings put global ro.HEAVY_WEIGHT_APP_ADJ 4
    adb shell settings put global ro.app.optimization true
    adb shell settings put global ro.launcher.dynamic true
    adb shell settings put global ro.launcher.label.fastupdate true
    adb shell settings put global device_idle_constants idle_duration=0
    adb shell settings put global hidden_api_policy 1
    adb shell settings put global hidden_api_policy_p_apps 1
    adb shell settings put global hidden_api_policy_pre_p_apps 1
    adb shell settings put global show_hidden_icon_apps_enabled 1
    adb shell settings put global persist.omh.enabled 0
    adb shell settings put global persist.service.lgospd.enable 0
    adb shell settings put global persist.service.pcsync.enable 0
    adb shell settings put global persist.sys.ssr.enable_debug 0
    adb shell settings put global persist.sys.ssr.enable_ramdumps 0
    adb shell settings put global persist.sys.ssr.restart_level 1
    adb shell settings put global persist.sys.ap.restart_level 1
    adb shell settings put global persist.sys.enable_strategy true
    adb shell settings put global persist.rcs.supported 0
    adb shell settings put global persist.data.profile_update true
    adb shell settings put global persist.data.mode concurrent
    adb shell settings put global persist.data.netmgrd.qos.enable true
    adb shell settings put global persist.data.tcpackprio.enable true
    adb shell settings put global persist.data.iwlan.enable true
    adb shell settings put global persist.data.wda.enable true
    adb shell settings put global persist.rmnet.data.enable true
    adb shell settings put global persist.net.doxlat true
    adb shell settings put global ro.use_data_netmgrd true
    adb shell settings put global ro.com.android.dataroaming false
    adb shell settings put global ro.ril.enable.managed.roaming 0
    adb shell settings put global ro.wcn enabled
    adb shell settings put global ro.config.ehrpd true
    adb shell settings put global debug.bt.lowspeed true
    adb shell settings put global debug.bt.discoverable_time 0
    adb shell settings put global ro.ril.avoid.pdp.overlap 1
    adb shell settings put global ro.ril.sensor.sleep.control 0
    adb shell settings put global ro.config.hw_ReduceSAR true
    adb shell settings put global radio_bounce 1
    adb shell settings put global persist.radio.NETWORK_SWITCH 2
    adb shell settings put global persist.radio.no_wait_for_card 1
    adb shell settings put global persist.radio.data_no_toggle 1
    adb shell settings put global persist.radio.data_con_rprt true
    adb shell settings put global persist.radio.data_ltd_sys_ind 1
    adb shell settings put global persist.radio.add_power_save 1
    adb shell settings put global persist.radio.jbims 1
    adb shell settings put global persist.ril.uart.flowctrl 99
    adb shell settings put global persist.sys.gz.enable false
    adb shell settings put global persist.gps.qc_nlp_in_use 0
    adb shell settings put global hw.nogps true
    adb shell settings put global assisted_gps_enabled 0
    adb shell settings put global ro.pip.gated 0
    adb shell settings put global ro.config.hw_gps_power_track false
    adb shell settings put global ro.config.hw_support_geofence false
    adb shell settings put global config.disable_location true
    adb shell settings put global location_mode 0
    adb shell settings put global location_global_kill_switch 1
    adb shell settings put global ro.support.signalsmooth true
    adb shell settings put global ro.config.combined_signal true
    adb shell settings put global ro.allow.mock.location 1
    adb shell settings put global ro.com.google.locationfeatures 0
    adb shell settings put global ro.com.google.networklocation 0
    adb shell settings put global ro.gps.agps_provider 0
    adb shell settings put global ro.ril.def.agps.feature 0
    adb shell settings put global ro.ril.def.agps.mode 0
    adb shell settings put global ro.vendor.net.enable_sla 1
    adb shell settings put global net.tethering.noprovisioning true
    adb shell settings put global security.perf_harden 0
    adb shell settings put global persist.sys.resolution_change 1
    adb shell settings put global ro.vendor.display.mode_change_optimize.enable true
    adb shell settings put global ro.vendor.display.switch_resolution.support 1
    adb shell settings put global ro.vendor.display.video_or_camera_fps.support true
    adb shell settings put global ro.vendor.fps.switch.thermal true
    adb shell settings put global ro.surface_flinger.protected_contents true
    adb shell settings put global ro.surface_flinger.force_hwc_copy_for_virtual_displays true
    adb shell settings put global ro.surface_flinger.running_without_sync_framework false
    adb shell settings put global ro.surface_flinger.supports_background_blur 0
    adb shell settings put global ro.surface_flinger.support_kernel_idle_timer true
    adb shell settings put global ro.surface_flinger.set_display_power_timer_ms 100
    adb shell settings put global ro.surface_flinger.set_idle_timer_ms 250
    adb shell settings put global ro.surface_flinger.set_touch_timer_ms 500
    adb shell settings put global ro.surface_flinger.set_fps_stat_timer_ms 750
    adb shell settings put global ro.surface_flinger.vsync_event_phase_offset_ns 0
    adb shell settings put global ro.surface_flinger.vsync_sf_event_phase_offset_ns 0
    adb shell settings put global ro.surface_flinger.present_time_offset_from_vsync_ns 0
    adb shell settings put global ro.surface_flinger.use_content_detection_for_refresh_rate true
    adb shell settings put global ro.surface_flinger.refresh_rate_switching true
    adb shell settings put global ro.surface_flinger.enable_layer_caching true
    adb shell settings put global ro.surface_flinger.layer_caching_active_layer_timeout_ms 0
    adb shell settings put global ro.surface_flinger.use_context_priority true
    adb shell settings put global ro.surface_flinger.start_graphics_allocator_service true
    adb shell settings put global ro.surface_flinger.uclamp.min 0
    adb shell settings put global ro.surface_flinger.max_frame_buffer_acquired_buffers 1
    adb shell settings put global ro.surface_flinger.has_wide_color_display false
    adb shell settings put global persist.sys.color.adaptive true
    adb shell settings put global persist.sys.sf.color_saturation 1.0
    adb shell settings put global persist.sys.brightness.low.gamma true
    adb shell settings put global persist.sys.sf.native_mode 2
    adb shell settings put global persist.sys.sf.hs_mode 0
    adb shell settings put global persist.sys.sf.disable_blurs 1
    adb shell settings put global persist.sys.static_blur_mode false
    adb shell settings put global persist.sys.disable_blur_view true
    adb shell settings put global persist.perf.wm_static_blur true
    adb shell settings put global sys.output.10bit true
    adb shell settings put global sys.fb.bits 32
    adb shell settings put global persist.sys.shadow.open 0
    adb shell settings put global persist.sys.use_16bpp_alpha 0
    adb shell settings put global persist.sys.purgeable_assets 0
    adb shell settings put global persist.sys.scrollingcache 2
    adb shell settings put global ro.vendor.perf.scroll_opt true
    adb shell settings put global ro.vendor.perf.scroll_opt.heavy_app true
    adb shell settings put global ro.vendor.scroll.preobtain.enable true
    adb shell settings put global vendor.perf.gestureflingboost.enable true
    adb shell settings put global ro.min_pointer_dur 1
    adb shell settings put global ro.max.fling_velocity 12000
    adb shell settings put global ro.min.fling_velocity 4000
    adb shell settings put global windowsmgr.max_events_per_sec 150
    adb shell settings put global ro.launcher.blur.appLaunch 0
    adb shell settings put global iop.enable_prefetch_ofr 1
    adb shell settings put global iop.enable_uxe 1
    adb shell settings put global iop.enable_iop 1
    adb shell settings put global vendor.perf.iop_v3.enable true
    adb shell settings put global vendor.perf.iop_v3.enable.debug false
    adb shell settings put global vendor.perf.workloadclassifier.enable true
    adb shell settings put global ro.vendor.iocgrp.config 1
    adb shell settings put global persist.sys.autoclearsave 2
    adb shell settings put global persist.sys.enable_ioprefetch true
    adb shell settings put global persist.mm.enable.prefetch true
    adb shell settings put global mm.enable.smoothstreaming true
    adb shell settings put global debug.media.video.frc false
    adb shell settings put global debug.media.video.vpp false
    adb shell settings put global sys.media.vdec.sw 1
    adb shell settings put global ro.vendor.media_performance_class 0
    adb shell settings put global ro.config.hw_media_flags 2
    adb shell settings put global ro.mediaScanner.enable false
    adb shell settings put global ro.media.maxresolution 0
    adb shell settings put global ro.media.dec.aud.wma.enabled 1
    adb shell settings put global ro.media.dec.vid.wmv.enabled 1
    adb shell settings put global media.stagefright.thumbnail.prefer_hw_codecs true
    adb shell settings put global media.stagefright.use-awesome true
    adb shell settings put global media.stagefright.enable-record false
    adb shell settings put global media.stagefright.enable-scan false
    adb shell settings put global media.stagefright.enable-meta true
    adb shell settings put global media.stagefright.enable-http true
    adb shell settings put global media.enable-commonsource true
    adb shell settings put global persist.media.lowlatency.enable true
    adb shell settings put global persist.media.hls.enhancements true
    adb shell settings put global persist.media.treble_omx false
    adb shell settings put global av.debug.disable.pers.cache 0
    adb shell settings put global aaudio.mmap_policy 1
    adb shell settings put global aaudio.mmap_exclusive_policy 2
    adb shell settings put global audio.legacy.postproc true
    adb shell settings put global audio.deep_buffer.media true
    adb shell settings put global audio.parser.ip.buffer.size 0
    adb shell settings put global audio.offload.video true
    adb shell settings put global audio.offload.track.enable true
    adb shell settings put global audio.offload.passthrough false
    adb shell settings put global audio.offload.gapless.enabled true
    adb shell settings put global audio.offload.multiple.enabled true
    adb shell settings put global audio.offload.pcm.16bit.enable false
    adb shell settings put global audio.offload.pcm.24bit.enable false
    adb shell settings put global audio.track.enablemonoorstereo 1
    adb shell settings put global ro.have_aacencode_feature 1
    adb shell settings put global ro.vendor.audio_tunning.nr 1
    adb shell settings put global vendor.audio.lowpower true
    adb shell settings put global vendor.audio.use.sw.alac.decoder true
    adb shell settings put global vendor.audio.use.sw.ape.decoder true
    adb shell settings put global lpa.use-stagefright true
    adb shell settings put global lpa.decode false
    adb shell settings put global lpa.encode false
    adb shell settings put global tunnel.decode false
    adb shell settings put global tunnel.encode false
    adb shell settings put global persist.sys.audio.source true
    adb shell settings put global persist.speaker.prot.enable false
    adb shell settings put global persist.audio.hp true
    adb shell settings put global persist.audio.hifi true
    adb shell settings put global ro.config.hifi_always_on true
    adb shell settings put global ro.config.hifi_enhance_support 1
    adb shell settings put global ro.vendor.audio.game.effect true
    adb shell settings put global ro.vendor.audio.spk.clean true
    adb shell settings put global ro.audio.soundfx.dirac true
    adb shell settings put global audio.sys.routing.latency 0
    adb shell settings put global audio.sys.mute.latency.factor 2
    adb shell settings put global mpq.audio.decode true
    adb shell settings put global debug.stagefright.ccodec 1
    adb shell settings put global debug.stagefright.omx_default_rank 0
    adb shell settings put global debug.stagefright.omx_default_rank.sw-audio 1
    adb shell settings put global vendor.media.omx 0
    adb shell settings put global af.fast_track_multiplier 1
    adb shell settings put global af.thread.throttle 0
    adb shell settings put global ota_disable_automatic_update 1
    adb shell settings put global drm.service.enabled true
    adb shell settings put global vendor.hwc.drm.scale_with_gpu 1
    adb shell settings put global persist.vendor.firmware.update true
    adb shell settings put global persist.vendor.battery.health true
    adb shell settings put global persist.vendor.battery.health.optimise true
    adb shell settings put global persist.vendor.accelerate.charge true
    adb shell settings put global persist.vendor.low.cutoff true
    adb shell settings put global persist.vendor.cool.mode true
    adb shell settings put global persist.vendor.cne.feature 1
    adb shell settings put global persist.vendor.dpm.feature 1
    adb shell settings put global persist.vendor.dpm.tcm 1
    adb shell settings put global persist.vendor.dc.enable 2
    adb shell settings put global persist.sys.support.vt false
    adb shell settings put global persist.sys.softdetector.enable false
    adb shell settings put global ro.sf.use_latest_hwc_vsync_period 1
    adb shell settings put global ro.sf.blurs_are_expensive 0
    adb shell settings put global ro.sf.compbypass.enable 1
    adb shell settings put global ro.compcache.default 1
    adb shell settings put global enable_gpu_debug_layers 0
    adb shell settings put global sys.tp.grip_enable 1
    adb shell settings put global sys.use_fifo_ui 1
    adb shell settings put global sys_vdso 1
    adb shell settings put global sys.enable_lpm 1
    adb shell settings put global ro.vndk.lite true
    adb shell settings put global ro.recentMode 0
    adb shell settings put global persist.vendor.enable.hans true
    adb shell settings put global ro.amlogic.no.preloadclass 0
    adb shell settings put global ro.config.rm_preload_enabled 1
    adb shell settings put global ro.storage_manager.enabled true
    adb shell settings put global storage_preload 1
    adb shell settings put global storage.preload.complete 1
    adb shell settings put global persist.dummy_storage 1
    adb shell settings put global persist.sys.storage_preload 1
    adb shell settings put global persist.sys.prelaunch.off 0
    adb shell settings put global persist.sys.preloads.file_cache_expired 0
    adb shell settings put global persist.vendor.enable.preload true
    adb shell settings put global persist.preload.common 1
    adb shell settings put global enable_app_prefetch 1
    adb shell settings put global ro.quick_start_support 1
    adb shell settings put global ro.zygote.preload.enable 1
    adb shell settings put global ro.zygote.preload.disable 2
    adb shell settings put global ro.zygote.disable_gl_preload false
    adb shell settings put global persist.zygote.preload_threads 2
    adb shell settings put global persist.sys.preload.preload_num 2
    adb shell settings put global persist.sys.preLoadDrawable.debug false
    adb shell settings put global persist.sys.preLoadDrawable.enable true
    adb shell settings put global persist.sys.boost.launch 1
    adb shell settings put global persist.sys.powersave.rotate 1
    adb shell settings put global persist.irqbalance.enable true
    adb shell settings put global persist.device_config.runtime_native.use_app_image_startup_cache true
    adb shell settings put global persist.device_config.runtime_native.usap_pool_enabled true
    adb shell settings put global persist.device_config.runtime_native.usap_pool_size_min 1
    adb shell settings put global persist.device_config.runtime_native.usap_refill_threshold 1
    adb shell settings put global persist.device_config.runtime_native_boot.iorap_readahead_enable true
    adb shell settings put global persist.device_config.runtime_native_boot.iorap_perfetto_enable false
    adb shell settings put global persist.device_config.runtime_native.metrics.reporting-mods 0
    adb shell settings put global persist.device_config.runtime_native.metrics.reporting-mods-server 0
    adb shell settings put global persist.device_config.runtime_native.metrics.write-to-statsd false
    adb shell settings put global ro.service.remove_unused 1
    adb shell settings put global ro.iorapd.enable true
    adb shell settings put global iorapd.perfetto.enable false
    adb shell settings put global iorapd.readahead.enable true
    adb shell settings put global ro.kernel.ebpf.supported true
    adb shell settings put global sys.ipo.disable 0
    adb shell settings put global ro.mtk_ipo_support 1
    adb shell settings put global ro.mtk_perfservice_support 1
    adb shell settings put global ro.mtk_bg_power_saving_support 1
    adb shell settings put global ro.mtk_bg_power_saving_ui 1
    adb shell settings put global vendor.mtk_thumbnail_optimization true
    adb shell settings put global def_bg_power_saving 1
    adb shell settings put global persist.bg.dexopt.enable true
    adb shell settings put global persist.sys.ps.enable 1
    adb shell settings put global background_gpu_usage 0
    adb shell settings put global persist.sys.gamespeed.enable true
    adb shell settings put global sys.games.gt.prof 1
    adb shell settings put global ro.config.gameassist 1
    adb shell settings put global debug.game.video.support true
    adb shell settings put global debug.enable.gamed 1
    adb shell settings put global debug.slsi_platform 1
    adb shell settings put global debug.sqlite.journalmode OFF
    adb shell settings put global debug.sqlite.syncmode OFF
    adb shell settings put global debug.sqlite.wal.syncmode OFF
    adb shell settings put global ro.vendor.gpu.dataspace 1
    adb shell settings put global ro.incremental.enable 1
    adb shell settings put global ro.fb.mode 1
    adb shell settings put global ro.tb.mode 1
    adb shell settings put global ro.ril.hsupa.category 6
    adb shell settings put global ro.ril.hsdpa.category 8
    adb shell settings put global ro.ril.gprsclass 10
    adb shell settings put global ro.ril.hsdpa.dbdc 1
    adb shell settings put global ro.ril.hsxpa 2
    adb shell settings put global ro.ril.enable.sdr 0
    adb shell settings put global ro.ril.enable.a52 1
    adb shell settings put global ro.ril.enable.dtm 0
    adb shell settings put global ro.ril.enable.amr.wideband 1
    adb shell settings put global ro.ril.enable.imc.feature 1
    adb shell settings put global ro.ril.enable.enhance.search 1
    adb shell settings put global ro.ril.enable.pre_r8fd 1
    adb shell settings put global ro.ril.enable.nitz 0
    adb shell settings put global ro.ril.disable.cpc 1
    adb shell settings put global ro.ril.fast.dormancy.rule 0
    adb shell settings put global ro.fast.dormancy 0
    adb shell settings put global ro.product.enhanced_4g_lte true
    adb shell settings put global ro.telephony.call_ring.multiple false
    adb shell settings put global sys.fflag.override.settings_seamless_transfer true
    adb shell settings put global persist.vendor.data.mode offload
    adb shell settings put global persist.vendor.mwqem.enable 1
    adb shell settings put global vendor.debug.egl.swapinterval 0
    adb shell settings put global debug.gr.swapinterval 0
    adb shell settings put global ro.vold.umsdirtyratio 1
    adb shell settings put global debug.cpuprio 1
    adb shell settings put global debug.gpuprio 1
    adb shell settings put global debug.ioprio 1
    adb shell settings put global debug.hang.count 0
    adb shell settings put global debug.kill_allocating_task 1
    adb shell settings put global ro.config.upgrade_appkill true
    adb shell settings put global ro.lmk.kill_heaviest_task true
    adb shell settings put global ro.lmk.use_minfree_levels true
    adb shell settings put global ro.lmk.vmpressurenhanced true
    adb shell settings put global persist.vendor.memplus.enable 1
    adb shell settings put global persist.sys.ramboost.enable true
    adb shell settings put global persist.sys.ramboost.ioppreload true
    adb shell settings put global persist.sys.ramboost.olmemplus_option 2
    adb shell settings put global persist.sys.memctrl on
    adb shell settings put global ro.memperf.enable true
    adb shell settings put global native_memtag_sync 1
    adb shell settings put global ram_expand_size_list 1
    adb shell settings put global sys.is_mem_low_level 1
    adb shell settings put global sys.use_memfd true
    adb shell settings put global sys.config.bigdata_enable true
    adb shell settings put global sys.config.bigdata_mem_enable true
    adb shell settings put global ro.config.per_app_memcg true
    adb shell settings put global ro.config.low_mem true
    adb shell settings put global ro.config.low_ram true
    adb shell settings put global ro.config.low_ram.mod true
    adb shell settings put global ro.board_ram_size low
    adb shell settings put global ro.ime.lowmemory true
    adb shell settings put global ro.am.enabled_low_mem_maint true
    adb shell settings put global ro.am.no_kill_cached_processes_until_boot_completed true
    adb shell settings put global ro.am.no_kill_cached_processes_post_boot_completed_duration_millis 0
    adb shell settings put global ro.ksm.default 1
    adb shell settings put global ro.cp_system_other_odex 1
    adb shell settings put global ro.config.hw_pg_frz_all true
    adb shell settings put global ro.config.dha_pwhitelist_enable 1
    adb shell settings put global ro.config.dha_tunnable 1
    adb shell settings put global ro.has.cpu.setting true
    adb shell settings put global ro.cpufreq.game 1
    adb shell settings put global ro.core_ctl_min_cpu 0
    adb shell settings put global ro.core_ctl_present 1
    adb shell settings put global ro.thermal_warmreset true
    adb shell settings put global ro.config.enable_thermal_bdata true
    adb shell settings put global persist.sys.thermal_policy_update 1
    adb shell settings put global persist.sys.thermal.enable 1
    adb shell settings put global persist.thermalmanager.enable true
    adb shell settings put global thermal_offload 0
    adb shell settings put global allow_heat_cooldown_always 1
    adb shell settings put global persist.sys.lowcost 1
    adb shell settings put global persist.sys.binary_xml false
    adb shell settings put global unused_static_shared_lib_min_cache_period_ms 250
    adb shell settings put global cached_apps_freezer enabled
    adb shell settings put global persist.device_config.use_cgroup_freezer true
    adb shell settings put global app_restriction_enabled true
    adb shell settings put global app_auto_restriction_enabled 1
    adb shell settings put global app_standby_enabled 1
    adb shell settings put global forced_app_standby_enabled 1
    adb shell settings put global keep_profile_in_background 0
    adb shell settings put global always_finish_activities 1
    adb shell settings put global sys.app.oom_adj 1
    adb shell settings put global sys.isdumpstaterunning 0
    adb shell settings put global sys.config.spcm_enable true
    adb shell settings put global sys.config.samp_spcm_enable true
    adb shell settings put global sys.config.spcm_preload_enable true
    adb shell settings put global sys.config.spcm_kill_skip true
    adb shell settings put global sys.config.spcm_gcm_kill_enable false
    adb shell settings put global sys.config.spcm_db_enable false
    adb shell settings put global sys.config.spcm_db_launcher false
    adb shell settings put global sys.config.samp_oak_enable false
    adb shell settings put global sys.config.samp_oakoom_enable false
    adb shell settings put global sys.settings.support 1
    adb shell settings put global persist.sys.ss.enable false
    adb shell settings put global persist.sys.pwctl.enable 0
    adb shell settings put global sys.ipo.pwrdncap 0
    adb shell settings put global dynamic_power_savings_enabled 1
    adb shell settings put global adaptive_battery_management_enabled 0
    adb shell settings put global battery_tip_constants app_restriction_enabled=true
    adb shell settings put global battery_stats_constants track_cpu_times_by_proc_state=false
    adb shell settings put global battery_saver_constants "vibration_disabled=true,animation_disabled=true,soundtrigger_disabled=true,fullbackup_deferred=true,keyvaluebackup_deferred=true,gps_mode=low_power,data_saver=true,optional_sensors_disabled=true,advertiser_id_enabled=false,force_all_apps_standby=true,launch_boost_disabled=false"
    adb shell settings put global sched.colocate.enable 1
    adb shell settings put global debug.smart_scheduling 1
    adb shell settings put global persist.sys.io_scheduler noop
    adb shell settings put global sys.io.scheduler noop
    adb shell settings put global sys.start.first 1
    adb shell settings put global ro.am.reschedule_service true
    adb shell settings put global ro.sys.fw.bservice_enable true
    adb shell settings put global ro.sys.fw.force_adoptable true
    adb shell settings put global debug.hwui.disable_vsync 0
    adb shell settings put global debug.hwui.disable_gpu_cache false
    adb shell settings put global cache.trigger 1
    adb shell settings put global service.sf.prime_shader_cache 1
    adb shell settings put global service.sf.present_timestamp 0
    adb shell settings put global persist.sys.engpc.disable 0
    adb shell settings put global persist.enable_task_snapshots false
    adb shell settings put global ro.config.fha_enable true
    adb shell settings put global ro.config.enable_rcc true
    adb shell settings put global ro.config.sync 0
    adb shell settings put global max_empty_time_millis 0
    adb shell settings put global fstrim_mandatory_interval 1
    adb shell settings put global ro.sys.fw.use_trim_settings true
    adb shell settings put global ro.sys.fw.trim_empty_percent 50
    adb shell settings put global ro.sys.fw.trim_cache_percent 50
    adb shell settings put global ro.sys.fw.empty_app_percent 25
    adb shell settings put global ro.trim.config true
    adb shell settings put global ro.trim.memory.launcher 1
    adb shell settings put global ro.trim.memory.font_cache 1
    adb shell settings put global ro.zstd.default_compression_level 1
    adb shell settings put global vold.post_fs_data_done 1
    adb shell settings put global vold.storage.prepared 1
    adb shell settings put global vold.has_compress 1
    adb shell settings put global vold.has_quota 0
    adb shell settings put global vold.should_defrag 1
    adb shell settings put global vold.checkpoint_committed 1
    adb shell settings put global ro.storaged.event.interval 999999
    adb shell settings put global gadget.nand.force_sync true
    adb shell settings put global virtualsd.enable true
    adb shell settings put global pm.sdwake.enabled true
    adb shell settings put global ro.DontUseAnimate yes
    adb shell settings put global debug.javafx.animation.fullspeed true
    adb shell settings put global debug.hwui.force_dark true
    adb shell settings put global debug.hwui.perfetto_profile_mode both
    adb shell settings put global debug.performance.tuning 1
    adb shell settings put global debug.gralloc.map_fb_memory 1
    adb shell settings put global debug.gralloc.enable_fb_ubwc 1
    adb shell settings put global debug.gralloc.gfx_ubwc_disable 0
    adb shell settings put global debug.gralloc.disable_ahardware_buffer 1
    adb shell settings put global debug.gr.numframebuffers 1
    adb shell settings put global persist.smart_pool 1
    adb shell settings put global ro.hardware.gralloc default
    adb shell settings put global ro.hardware.respect_als true
    adb shell settings put global ro.hardware.hwcomposer default
    adb shell settings put global ro.hwui.render_ahead 1
    adb shell settings put global debug.hwui.renderer_mode 1
    adb shell settings put global debug.hwui.level 0
    adb shell settings put global debug.hwui.swap_with_damage false
    adb shell settings put global debug.hwui.render_dirty_regions false
    adb shell settings put global debug.hwui.show_dirty_regions false
    adb shell settings put global debug.hwui.use_gpu_pixel_buffers false
    adb shell settings put global debug.hwui.disabledither true
    adb shell settings put global debug.hwui.disable_draw_defer true
    adb shell settings put global debug.hwui.disable_draw_reorder true
    adb shell settings put global debug.hwui.show_draw_order 0
    adb shell settings put global debug.hwui.show_draw_calls 0
    adb shell settings put global debug.hwui.enable_bp_cache true
    adb shell settings put global debug.hwui.use_small_cache 1
    adb shell settings put global sysui_tuner_enabled 0
    adb shell settings put global sysui_font_cache_persist true
    adb shell settings put global persist.sys.font 2
    adb shell settings put global persist.sys.font_clarity 0
    adb shell settings put global persist.sys.force_highendgfx true
    adb shell settings put global ro.config.avoid_gfx_accel false
    adb shell settings put global rs.gpu.rsIntrinsic 0
    adb shell settings put global rs.gpu.filterscript 0
    adb shell settings put global rs.gpu.renderscript 0
    adb shell settings put global debug.rs.debug 0
    adb shell settings put global debug.rs.visual 0
    adb shell settings put global debug.rs.reduce 1
    adb shell settings put global debug.rs.shader 0
    adb shell settings put global debug.rs.shader.attributes 0
    adb shell settings put global debug.rs.shader.uniforms 0
    adb shell settings put global ro.graphics.hwcomposer.kvm true
    adb shell settings put global fku.perf.profile 1
    adb shell settings put global graphics.gpu.profiler.support true
    adb shell settings put global force_gpu_render 1
    adb shell settings put global force_gpu_rendering 1
    adb shell settings put global gpu_rendering_mode 1
    adb shell settings put global opengl_renderer 1
    adb shell settings put global opengl_trace false
    adb shell settings put global vendor.display.enable_fb_scaling 1
    adb shell settings put global vendor.display.use_layer_ext 1
    adb shell settings put global vendor.display.enable_posted_start_dyn 1
    adb shell settings put global vendor.display.comp_mask 0
    adb shell settings put global vendor.display.enable_perf_hint_large_comp_cycle 1
    adb shell settings put global vendor.display.disable_decimation 0
    adb shell settings put global vendor.display.disable_ui_3d_tonemap 1
    adb shell settings put global vendor.display.enable_rotator_ui 1
    adb shell settings put global vendor.display.skip_refresh_rate_change 1
    adb shell settings put global sdm.perf_hint_window 50
    adb shell settings put global ro.mtk_perf_fast_start_win 1
    adb shell settings put global ro.mtk_perf_simple_start_win 1
    adb shell settings put global ro.mtk_perf_response_time 1
    adb shell settings put global persist.sys.max_rdh_delay 0
    adb shell settings put global persist.sys.performance true
    adb shell settings put global persist.sys.cpuset.enable 1
    adb shell settings put global persist.sys.cpuset.subswitch 1
    adb shell settings put global persist.sys.iaware.cpuenable true
    adb shell settings put global persist.sys.iaware.vsyncfirst true
    adb shell settings put global persist.sys.enable_iaware true
    adb shell settings put global persist.sys.periodic.enable true
    adb shell settings put global persist.tuning.qdcm 1
    adb shell settings put global sys.iaware.eas.on true
    adb shell settings put global debug.force_no_blanking true
    adb shell settings put global ro.bq.gpu_to_cpu_unsupported 1
    adb shell settings put global ro.product.gpu.driver 1
    adb shell settings put global ro.vendor.gpu.boost 1
    adb shell settings put global multi_sampling_enabled 0
    adb shell settings put global persist.sampling_profiler 0
    adb shell settings put global dev.pm.dyn_samplingrate 1
    adb shell settings put global cpu.fps auto
    adb shell settings put global gpu.fps auto
    adb shell settings put global persist.sys.fpsctrl.enable 1
    adb shell settings put global persist.sys.autofps.mode 1
    adb shell settings put global sys.perf.heavy false
    adb shell settings put global sys.perf.status false
    adb shell settings put global sys.perf.zygote true
    adb shell settings put global sys.perf.iop true
    adb shell settings put global sys.perf.schd true
    adb shell settings put global sys.perf.hmp 6:2
    adb shell settings put global sys.perf.fbooster true
    adb shell settings put global sys.perf.tbooster true
    adb shell settings put global sys.hwc.gpu_perf_mode 1
    adb shell settings put global ro.qualcomm.perf.cores_online 2
    adb shell settings put global ro.hw.use_hwc_cpu_perf_mode 1
    adb shell settings put global ro.hw.use_disable_composition_type_gles 0
    adb shell settings put global ro.hwc.legacy_api true
    adb shell settings put global hwc.scenario 2
    adb shell settings put global hw2d.force 1
    adb shell settings put global hw3d.force 1
    adb shell settings put global persist.sys.force_hw_ui true
    adb shell settings put global persist.sys.ui.hw 1
    adb shell settings put global persist.sys.oem_smooth 1
    adb shell settings put global persist.sys.force_sw_gles 1
    adb shell settings put global ro.kernel.qemu.gles 1
    adb shell settings put global ro.config.hw_wfd_optimize true
    adb shell settings put global persist.sys.wfd.virtual 0
    adb shell settings put global persist.sys.jankenable false
    adb shell settings put global persist.hwc.ptor.enable true
    adb shell settings put global persist.hwc.mdpcomp.enable true
    adb shell settings put global persist.hwc.pubypass true
    adb shell settings put global persist.hwc2.skip_client_color_transform true
    adb shell settings put global com.qc.hardware true
    adb shell settings put global debug.qc.hardware true
    adb shell settings put global debug.composition.type gpu
    adb shell settings put global debug.cpurend.vsync true
    adb shell settings put global debug.gpurend.vsync true
    adb shell settings put global debug.enabletr true
    adb shell settings put global debug.enable.gldebug 0
    adb shell settings put global debug.sf.layer_timeout 0
    adb shell settings put global debug.sf.layer_smoothness 1
    adb shell settings put global debug.sf.no_hw_vsync 0
    adb shell settings put global debug.sf.ddms 0
    adb shell settings put global debug.sf.hw 1
    adb shell settings put global debug.sf.enable_hgl 1
    adb shell settings put global debug.sf.enable_hwc_vds 0
    adb shell settings put global debug.sf.swaprect 1
    adb shell settings put global debug.sf.gpu_freq_index 1
    adb shell settings put global debug.sf.perf_mode 1
    adb shell settings put global debug.gfx.driver 1
    adb shell settings put global debug.gl.hw 1
    adb shell settings put global debug.egl.hw 1
    adb shell settings put global debug.egl.profiler 1
    adb shell settings put global debug.egl.force_msaa 1
    adb shell settings put global debug.egl.native_scaling 1
    adb shell settings put global debug.overlayui.enable 0
    adb shell settings put global debug.sf.gpuoverlay 0
    adb shell settings put global debug.sf.viewmotion 0
    adb shell settings put global debug.sf.high_fps_late_app_phase_offset_ns 0
    adb shell settings put global debug.sf.high_fps_late_sf_phase_offset_ns 0
    adb shell settings put global debug.sf.enable_advanced_sf_phase_offset 1
    adb shell settings put global debug.sf.enable_gl_backpressure 1
    adb shell settings put global debug.sf.latch_unsignaled 1
    adb shell settings put global debug.sf.auto_latch_unsignaled 0
    adb shell settings put global debug.sf.recomputecrop 0
    adb shell settings put global debug.sf.use_phase_offsets_as_durations 1
    adb shell settings put global debug.sf.disable_client_composition_cache 0
    adb shell settings put global debug.egl.buffcount 1
    adb shell settings put global debug.egl.debug_proc 0
    adb shell settings put global debug.egl.trace 0
    adb shell settings put global debug.egl.callstack 0
    adb shell settings put global debug.egl.finish 1
    adb shell settings put global debug.sf.showupdates 0
    adb shell settings put global debug.sf.showcpu 0
    adb shell settings put global debug.sf.showbackground 0
    adb shell settings put global debug.sf.showfps 0
    adb shell settings put global debug.sf.dump 0
    adb shell settings put global debug.sf.enable_egl_image_tracker 0
    adb shell settings put global debug.sf.predict_hwc_composition_strategy 1
    adb shell settings put global debug.sf.enable_planner_prediction true
    adb shell settings put global debug.sf.gpu_comp_tiling 1
    adb shell settings put global debug.enable.sglscale 1
    adb shell settings put global debug.qctwa.preservebuf 1
    adb shell settings put global debug.mdpcomp.idletime 0
    adb shell settings put global debug.mdpcomp.maxlayer 0
    adb shell settings put global debug.forceAutoTextureCompression 1
    adb shell settings put global debug.doze.component 0
    adb shell settings put global debug.migrate.bigcore false
    adb shell settings put global debug.sdm.support_writeback 1
    adb shell settings put global sdm.debug.disable_rotator_downscale 1
    adb shell settings put global sdm.debug.disable_skip_validate 1
    adb shell settings put global sdm.debug.disable_dest_sc 1
    adb shell settings put global sdm.debug.disable_scalar 1
    adb shell settings put global sdm.debug.disable_avr 1
    adb shell settings put global hotword_detection_enabled 0
    adb shell settings put global ro.hw.gyroscope false
    adb shell settings put global ro.config.hw_temperature_warn true
    adb shell settings put global ro.config.hw_sensorhub false
    adb shell settings put global ro.vendor.sensors.rawdata_mode false
    adb shell settings put global ro.vendor.sensors.pedometer false
    adb shell settings put global ro.vendor.sensors.step_counter false
    adb shell settings put global ro.vendor.sensors.step_detector false
    adb shell settings put global ro.vendor.sensors.pick_up false
    adb shell settings put global ro.vendor.sensors.gravity false
    adb shell settings put global ro.vendor.sensors.proximity false
    adb shell settings put global ro.vendor.sensors.facing false
    adb shell settings put global ro.vendor.sensors.multishake false
    adb shell settings put global ro.vendor.sensors.tilt_detector false
    adb shell settings put global ro.vendor.sensors.sta_detect false
    adb shell settings put global ro.vendor.sensors.mot_detect false
    adb shell settings put global ro.vendor.sensors.scrn_ortn false
    adb shell settings put global ro.vendor.sensors.dev_ori false
    adb shell settings put global ro.vendor.sensors.orientation false
    adb shell settings put global ro.vendor.sensors.laccel false
    adb shell settings put global ro.vendor.sensors.rotvec false
    adb shell settings put global ro.vendor.sensors.game_rv false
    adb shell settings put global ro.vendor.sensors.georv false
    adb shell settings put global ro.vendor.sensors.pam false
    adb shell settings put global ro.vendor.sensors.pug false
    adb shell settings put global ro.vendor.sensors.fns false
    adb shell settings put global ro.vendor.sensors.cmc false
    adb shell settings put global ro.vendor.sensors.dpc false
    adb shell settings put global ro.vendor.sensors.amd false
    adb shell settings put global ro.vendor.sensors.iod false
    adb shell settings put global ro.vendor.sensors.pmd false
    adb shell settings put global ro.vendor.sensors.rmd false
    adb shell settings put global ro.vendor.sensors.smd false
    adb shell settings put global ro.vendor.sensors.qmd false
    adb shell settings put global ro.vendor.sensors.vmd false
    adb shell settings put global ro.vendor.sensors.wu false
    adb shell settings put global ro.vendor.sensors.noneui false
    adb shell settings put global ro.vendor.sdk.sensors.gestures false
    adb shell settings put global ro.vendor.display.sensortype 0
    adb shell settings put global persist.vendor.sensors.enable.mag_filter true
    adb shell settings put global persist.sys.sensors.cfos false
    adb shell settings put global persist.sys.sensors.pug false
    adb shell settings put global persist.sys.sensors.spg false
    adb shell settings put global persist.radio.sar_sar_sensor false
    adb shell settings put global persist.radio.dynamic_sar false
    adb shell settings put global persist.metadata_dynfps.disable true
    adb shell settings put global persist.sys.doze_powersave true
    adb shell settings put global persist.android.strictmode 0
    adb shell settings put global persist.sys.strictmode.disable 1
    adb shell settings put global persist.sys.strictmode.visual 0
    adb shell settings put global persist.sys.strictmode.violation 0
    adb shell settings put global persist.sys.assert.enable false
    adb shell settings put global persist.sys.opbf.enable true
    adb shell settings put global persist.service.acm.enable 0
    adb shell settings put global hw.encoder.freerun 1
    adb shell settings put global hw.encoder.temp.enable 1
    adb shell settings put global hw.encoder.reencode.enable 0
    adb shell settings put global ro.hw.use_hwc_services 1
    adb shell settings put global ro.hw.use_secure_encoder_only 1
    adb shell settings put global ro.hw_timeout_multiplier 1
    adb shell settings put global vendor.display.enable_early_wakeup 1
    adb shell settings put global sys.config.phone_start_early true
    adb shell settings put global sys.config.activelaunch_enable true
    adb shell settings put global persist.sys.appstart.enable true
    adb shell settings put global persist.sys.appstart.sync true
    adb shell settings put global persist.sys.op_power_first_boot 1
    adb shell settings put global persist.sys.pre_bootloader yes
    adb shell settings put global persist.bootanim.preload 1
    adb shell settings put global ro.config.multi_task_enable true
    adb shell settings put global ro.config.max_starting_bg 2
    adb shell settings put global persist.added_boot_bgservices 2
    adb shell settings put global wait_for_debugger 0
    adb shell settings put global service.wait_for_bootanim 0
    adb shell settings put global service.bootvideo 0
    adb shell settings put global sys.boot.start_preload 1
    adb shell settings put global sys.boot.end_package 1
    adb shell settings put global sys.logbootcomplete 0
    adb shell settings put global dev.bootcomplete 0
    adb shell settings put global vendor.post_boot.parsed 1
    adb shell settings put global ro.quickboot.enable true
    adb shell settings put global ro.build.shutdown_timeout 0
    adb shell settings put global ro.warmboot.capability 1
    adb shell settings put global ro.boot.warranty_bit 0
    adb shell settings put global ro.oem_unlock_supported 1
    adb shell settings put global ro.platform.has.security true
    adb shell settings put global ro.security.reactive.active 2
    adb shell settings put global persist.security.ams.enforcing 0
    adb shell settings put global persist.sys.task_isolation false
    adb shell settings put global persist.sys.strict_op_enable false
    adb shell settings put global persist.sys.disable_rescue true
    adb shell settings put global sys.checkfs.fat false
    adb shell settings put global package_verifier_enable 0
    adb shell settings put global vendor.gatekeeper.disable_spu true
    adb shell settings put global ro.control_privapp_permissions enforce
    adb shell settings put global ro.config.dmverity false
    adb shell settings put global ro.config.rkp false
    adb shell settings put global ro.config.tima 0
    adb shell settings put global ro.profile.header 0
    adb shell settings put global ro.secure 0
    adb shell settings put global ro.build.selinux 0
    adb shell settings put global ro.build.selinux.enforce 0
    adb shell settings put global androidboot.selinux 0
    adb shell settings put global selinux.disabled true
    adb shell settings put global selinux.reload_policy 0
    adb shell settings put global ro.treble.enabled true
    adb shell settings put global ro.config.ksm.support true
    adb shell settings put global ro.wmt.blcr.enable 0
    adb shell settings put global ro.vendor.at_library true
    adb shell settings put global ro.vendor.gt_library true
    adb shell settings put global persist.sys.NV_FPSLIMIT 0
    adb shell settings put global persist.sys.NV_STEREOCTRL 0
    adb shell settings put global persist.sys.NV_STEREOSEPCHG 0
    adb shell settings put global persist.sys.NV_POWERMODE 2
    adb shell settings put global persist.sys.smart_power 2
    adb shell settings put global sys.fw.powermanager 1
    adb shell settings put global debug.power.monitor_tools false
    adb shell settings put global ro.product.use_charge_counter 1
    adb shell settings put global ro.charger.disable_init_blank true
    adb shell settings put global ro.config.hw_board_ipa true
    adb shell settings put global ro.config.hw_quickpoweron true
    adb shell settings put global ro.config.hw_power_saving true
    adb shell settings put global ro.config.hw_fast_dormancy 0
    adb shell settings put global ro.config.small_battery true
    adb shell settings put global ro.ril.power_collapse 1
    adb shell settings put global ro.pmqos.enable true
    adb shell settings put global ro.smps.enable true
    adb shell settings put global low_power 1
    adb shell settings put global low_power_sticky 1
    adb shell settings put global low_power_exceptions 1
    adb shell settings put global pm.sleep_mode 4
    adb shell settings put global power.saving.mode 2
    adb shell settings put global vendor.power.pasr.enabled true
    adb shell settings put global vendor.pasr.activemode.enabled true
    adb shell settings put global vendor.camera.lowpower.record.enable 1
    adb shell settings put global sys.autobrightness_optimize true
    adb shell settings put global ro.build.smartcharging 1
    adb shell settings put global accessibility_reduce_transparency 1
    adb shell settings put global heads_up_notifications_enabled 0
    adb shell settings put global enable_ephemeral_feature 0
    adb shell settings put global ro.workaround.noautofocus 1
    adb shell settings put global ro.screen.has.timeout false
    adb shell settings put global ro.charger.enable_suspend true
    adb shell settings put global LOCKSCREEN_AD_ENABLED 0
    adb shell settings put secure search_on_lockscreen_settings 0
    adb shell settings put secure lock_screen_allow_private_notifications 0
    adb shell settings put secure lock_screen_owner_info_enabled 0
    adb shell settings put secure lock_screen_lock_after_timeout 0
    adb shell settings put secure mount_ums_autostart 0
    adb shell settings put secure automatic_storage_manager_enabled 1
    adb shell settings put secure instant_apps_enabled 0
    adb shell settings put secure spell_checker_enabled 0
    adb shell settings put secure reduce_bright_colors_activated 1
    adb shell settings put secure adaptive_charging_enabled 0
    adb shell settings put secure screensaver_enabled 0
    adb shell settings put secure screensaver_activate_on_sleep 0
    adb shell settings put secure screensaver_activate_on_dock 0
    adb shell settings put secure camera_gesture_disabled 1
    adb shell settings put secure wake_gesture_enabled 0
    adb shell settings put secure volume_hush_gesture 0
    adb shell settings put secure hush_gesture_used 0
    adb shell settings put secure silence_gesture 0
    adb shell settings put secure skip_gesture 0
    adb shell settings put secure fingerprint_effect 0
    adb shell settings put secure touch_exploration_enabled 0
    adb shell settings put secure adaptive_sleep 0
    adb shell settings put secure game_auto_temperature_control 0
    adb shell settings put secure sensors_off 1
    adb shell settings put secure sensors_off_enabled 1
    adb shell settings put secure sensor_privacy 1
    adb shell settings put secure systemui.google.opa_enabled 0
    adb shell settings put secure ui_night_mode 2
    adb shell settings put secure night_display_auto_mode 0
    adb shell settings put secure theme_mode 2
    adb shell settings put system background_power_saving_enable 1
    adb shell settings put system perf_profile performance
    adb shell settings put system intelligent_sleep_mode 0
    adb shell settings put system power_mode high
    adb shell settings put system POWER_SAVE_PRE_CLEAN_MEMORY_TIME 0
    adb shell settings put system tube_amp_effect 1
    adb shell settings put system k2hd_effect 1
    adb shell settings put system support_dolby 1
    adb shell settings put system advanced_settings 1
    adb shell settings put system screen_auto_brightness_adj 0
    adb shell settings put system display_night_theme 1
    adb shell settings put system dark_theme 1
    adb shell settings put system font_scale 1.25
    adb shell settings put system auto_caps 0
    adb shell settings put system auto_punctuate 0
    adb shell settings put system auto_replace 0
    adb shell settings put system bluetooth_discoverability 0
    adb shell settings put system motion_engine 0
    adb shell settings put system master_motion 0
    adb shell settings put system motion_merged_mute_pause 0
    adb shell settings put system motion_overturn 0
    adb shell settings put system air_motion_engine 0
    adb shell settings put system air_motion_wake_up 0
    adb shell settings put system surface_palm_touch 0
    adb shell settings put system lift_to_wake 0
    adb shell settings put system charging_info_always 0
    adb shell settings put system notification_light_pulse 0
    adb shell settings put system vibrate_input_devices 0
    adb shell settings put system haptic_feedback_enabled 0
    adb shell service call sensor_privacy 9 i32 1
    adb shell service call sensor_privacy 8 i32 1
    adb shell service call sensor_privacy 4 i32 1
    adb shell am broadcast -a android.intent.action.ACTION_OPTIMIZE_DEVICE
    adb shell am broadcast -a com.android.systemui.action.CLEAR_MEMORY
    adb shell am kill-all
    adb shell cmd activity kill-all
    adb shell pm bg-dexopt-job
    echo "ALL DONE!"
    echo.
    adb kill-server
    echo.

    RMDIR /S /Q %USERPROFILE%\.android
    RMDIR /S /Q %USERPROFILE%\.dbus-keyrings
    pause
